spring.application.name=worker_ms

spring.cloud.aws.region.static=${AWS_REGION:us-east-1}

app.sqs.process-queue=process-queue
app.sqs.status-queue=video-status-queue
app.processing.fps=1
app.processing.work-dir=${java.io.tmpdir}/worker-ms
